export const data = [{"id":1,"animal_name":"Cheetah","animal_scientific":"Acinynox jubatus"},
{"id":2,"animal_name":"Shrike, common boubou","animal_scientific":"Laniarius ferrugineus"},
{"id":3,"animal_name":"Pigeon, wood","animal_scientific":"Columba palumbus"},
{"id":4,"animal_name":"Long-tailed jaeger","animal_scientific":"Stercorarius longicausus"},
{"id":5,"animal_name":"Antelope ground squirrel","animal_scientific":"Ammospermophilus nelsoni"},
{"id":6,"animal_name":"Magpie, black-backed","animal_scientific":"Gymnorhina tibicen"},
{"id":7,"animal_name":"Wolf spider","animal_scientific":"Lycosa godeffroyi"},
{"id":8,"animal_name":"Cobra (unidentified)","animal_scientific":"Naja sp."},
{"id":9,"animal_name":"Fox, silver-backed","animal_scientific":"Vulpes chama"},
{"id":10,"animal_name":"Plover, blacksmith","animal_scientific":"Vanellus armatus"},
{"id":11,"animal_name":"Lemur, sportive","animal_scientific":"Lepilemur rufescens"},
{"id":12,"animal_name":"Rattlesnake, eastern diamondback","animal_scientific":"Crotalus adamanteus"},
{"id":13,"animal_name":"Dromedary camel","animal_scientific":"Camelus dromedarius"},
{"id":14,"animal_name":"Dove, emerald-spotted wood","animal_scientific":"Turtur chalcospilos"},
{"id":15,"animal_name":"African pied wagtail","animal_scientific":"Motacilla aguimp"},
{"id":16,"animal_name":"Falcon, prairie","animal_scientific":"Falco mexicanus"},
{"id":17,"animal_name":"Lion, south american sea","animal_scientific":"Otaria flavescens"},
{"id":18,"animal_name":"Silver-backed fox","animal_scientific":"Vulpes chama"},
{"id":19,"animal_name":"Shark, blue","animal_scientific":"Prionace glauca"},
{"id":20,"animal_name":"Bird (unidentified)","animal_scientific":"unavailable"},
{"id":21,"animal_name":"Bear, polar","animal_scientific":"Ursus maritimus"},
{"id":22,"animal_name":"Agouti","animal_scientific":"Dasyprocta leporina"},
{"id":23,"animal_name":"Common boubou shrike","animal_scientific":"Laniarius ferrugineus"},
{"id":24,"animal_name":"Common long-nosed armadillo","animal_scientific":"Dasypus novemcinctus"},
{"id":25,"animal_name":"Violet-eared waxbill","animal_scientific":"Uraeginthus granatina"},
{"id":26,"animal_name":"Glossy starling (unidentified)","animal_scientific":"Lamprotornis sp."},
{"id":27,"animal_name":"Arctic tern","animal_scientific":"Sterna paradisaea"},
{"id":28,"animal_name":"Possum, pygmy","animal_scientific":"Acrobates pygmaeus"},
{"id":29,"animal_name":"Banded mongoose","animal_scientific":"Mungos mungo"},
{"id":30,"animal_name":"Devil, tasmanian","animal_scientific":"Sarcophilus harrisii"},
{"id":31,"animal_name":"Red-breasted cockatoo","animal_scientific":"Eolophus roseicapillus"},
{"id":32,"animal_name":"Jackal, silver-backed","animal_scientific":"Canis mesomelas"},
{"id":33,"animal_name":"Red-winged blackbird","animal_scientific":"Agelaius phoeniceus"},
{"id":34,"animal_name":"Ox, musk","animal_scientific":"Ovibos moschatus"},
{"id":35,"animal_name":"Bonnet macaque","animal_scientific":"Macaca radiata"},
{"id":36,"animal_name":"Leadbeateri's ground hornbill","animal_scientific":"Bucorvus leadbeateri"},
{"id":37,"animal_name":"Armadillo, nine-banded","animal_scientific":"Dasypus novemcinctus"},
{"id":38,"animal_name":"Macaque, rhesus","animal_scientific":"Macaca mulatta"},
{"id":39,"animal_name":"Campo flicker","animal_scientific":"Colaptes campestroides"},
{"id":40,"animal_name":"Creeper, black-tailed tree","animal_scientific":"Climacteris melanura"},
{"id":41,"animal_name":"Deer, red","animal_scientific":"Cervus elaphus"},
{"id":42,"animal_name":"Drongo, fork-tailed","animal_scientific":"Dicrurus adsimilis"},
{"id":43,"animal_name":"African lion","animal_scientific":"Panthera leo"},
{"id":44,"animal_name":"Brown hyena","animal_scientific":"Hyaena brunnea"},
{"id":45,"animal_name":"Asian false vampire bat","animal_scientific":"Megaderma spasma"},
{"id":46,"animal_name":"Eastern grey kangaroo","animal_scientific":"Macropus giganteus"},
{"id":47,"animal_name":"Long-crested hawk eagle","animal_scientific":"Lophoaetus occipitalis"},
{"id":48,"animal_name":"Boa, cook's tree","animal_scientific":"Corallus hortulanus cooki"},
{"id":49,"animal_name":"Lemur, grey mouse","animal_scientific":"Microcebus murinus"},
{"id":50,"animal_name":"Robin, kalahari scrub","animal_scientific":"Certotrichas paena"},
{"id":51,"animal_name":"Red and blue macaw","animal_scientific":"Ara chloroptera"},
{"id":52,"animal_name":"Buffalo, wild water","animal_scientific":"Bubalus arnee"},
{"id":53,"animal_name":"Common grenadier","animal_scientific":"Uraeginthus granatina"},
{"id":54,"animal_name":"Eastern diamondback rattlesnake","animal_scientific":"Crotalus adamanteus"},
{"id":55,"animal_name":"Coke's hartebeest","animal_scientific":"Alcelaphus buselaphus cokii"},
{"id":56,"animal_name":"White-fronted capuchin","animal_scientific":"Cebus albifrons"},
{"id":57,"animal_name":"Peccary, collared","animal_scientific":"Tayassu tajacu"},
{"id":58,"animal_name":"Porcupine, african","animal_scientific":"Hystrix cristata"},
{"id":59,"animal_name":"Tortoise, burmese brown mountain","animal_scientific":"Manouria emys"},
{"id":60,"animal_name":"Cereopsis goose","animal_scientific":"Cereopsis novaehollandiae"},
{"id":61,"animal_name":"Screamer, crested","animal_scientific":"Chauna torquata"},
{"id":62,"animal_name":"Pigeon, feral rock","animal_scientific":"Columba livia"},
{"id":63,"animal_name":"House sparrow","animal_scientific":"Passer domesticus"},
{"id":64,"animal_name":"Masked booby","animal_scientific":"Sula dactylatra"},
{"id":65,"animal_name":"Boa, mexican","animal_scientific":"Boa constrictor mexicana"},
{"id":66,"animal_name":"Black-throated butcher bird","animal_scientific":"Cracticus nigroagularis"},
{"id":67,"animal_name":"Rainbow lory","animal_scientific":"Trichoglossus haematodus moluccanus"},
{"id":68,"animal_name":"Jackal, black-backed","animal_scientific":"Canis mesomelas"},
{"id":69,"animal_name":"Southern right whale","animal_scientific":"Eubalaena australis"},
{"id":70,"animal_name":"White-throated toucan","animal_scientific":"Ramphastos tucanus"},
{"id":71,"animal_name":"Laughing kookaburra","animal_scientific":"Dacelo novaeguineae"},
{"id":72,"animal_name":"White-tailed deer","animal_scientific":"Odocoilenaus virginianus"},
{"id":73,"animal_name":"Crab, red lava","animal_scientific":"Graspus graspus"},
{"id":74,"animal_name":"Heron, green-backed","animal_scientific":"Butorides striatus"},
{"id":75,"animal_name":"Peccary, white-lipped","animal_scientific":"Tayassu pecari"},
{"id":76,"animal_name":"Eagle, pallas's fish","animal_scientific":"Haliaeetus leucoryphus"},
{"id":77,"animal_name":"White-faced tree rat","animal_scientific":"Echimys chrysurus"},
{"id":78,"animal_name":"Armadillo, nine-banded","animal_scientific":"Dasypus novemcinctus"},
{"id":79,"animal_name":"Lesser double-collared sunbird","animal_scientific":"Nectarinia chalybea"},
{"id":80,"animal_name":"Small-toothed palm civet","animal_scientific":"Arctogalidia trivirgata"},
{"id":81,"animal_name":"Otter, brazilian","animal_scientific":"Pteronura brasiliensis"},
{"id":82,"animal_name":"Wallaby, tammar","animal_scientific":"Macropus eugenii"},
{"id":83,"animal_name":"Pelican, great white","animal_scientific":"Pelecans onocratalus"},
{"id":84,"animal_name":"Squirrel, malabar","animal_scientific":"Ratufa indica"},
{"id":85,"animal_name":"Bushbaby, large-eared","animal_scientific":"Galago crassicaudataus"},
{"id":86,"animal_name":"Iguana, common green","animal_scientific":"Iguana iguana"},
{"id":87,"animal_name":"Puma","animal_scientific":"Felis concolor"},
{"id":88,"animal_name":"Snowy egret","animal_scientific":"Egretta thula"},
{"id":89,"animal_name":"Common seal","animal_scientific":"Phoca vitulina"},
{"id":90,"animal_name":"Snake, eastern indigo","animal_scientific":"Drymarchon corias couperi"},
{"id":91,"animal_name":"Helmeted guinea fowl","animal_scientific":"Numida meleagris"},
{"id":92,"animal_name":"Rabbit, eastern cottontail","animal_scientific":"Sylvilagus floridanus"},
{"id":93,"animal_name":"Bear, grizzly","animal_scientific":"Ursus arctos"},
{"id":94,"animal_name":"Miner's cat","animal_scientific":"Bassariscus astutus"},
{"id":95,"animal_name":"Starling, red-shouldered glossy","animal_scientific":"Lamprotornis nitens"},
{"id":96,"animal_name":"Owl, burrowing","animal_scientific":"Speotyte cuniculata"},
{"id":97,"animal_name":"Lechwe, kafue flats","animal_scientific":"Kobus leche robertsi"},
{"id":98,"animal_name":"Possum, western pygmy","animal_scientific":"Cercatetus concinnus"},
{"id":99,"animal_name":"Northern elephant seal","animal_scientific":"Mirounga angustirostris"},
{"id":100,"animal_name":"Yellow baboon","animal_scientific":"Papio cynocephalus"}]